//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAmbition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanTin
    {
        public int MaBanTin { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDang { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaXe { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<bool> HanDang { get; set; }
    
        public virtual Xe Xe { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
