//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAmbition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.BangTams = new HashSet<BangTam>();
            this.BanTins = new HashSet<BanTin>();
            this.PhanQuyens = new HashSet<PhanQuyen>();
        }
    
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string XacNhanMatKhau { get; set; }
    
        public virtual ICollection<BangTam> BangTams { get; set; }
        public virtual ICollection<BanTin> BanTins { get; set; }
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
    }
}
