//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAmbition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaQuyen { get; set; }
        public string TaiKhoan { get; set; }
        public string MoTa { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
